services:
  mysql:
    image: mysql:latest
    container_name: pornthipcrapejeah-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pornthipcrapejeah
      MYSQL_DATABASE: jpcrape_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: